---
- name: Install Jenkins
  hosts: jenkins
  gather_facts: no
  become: yes

  vars:
          jenkins_state: present  # present or absent
          jenkins_version: "2.204.5"  # 2.204.5 released on 2020/03/07
          jenkins_pkg_url: "http://pkg.jenkins.io/debian-stable/binary"
          jenkins_http_port: 8080  # port to run jenkins on
          jenkins_init_file: /etc/default/jenkins # contains global settings for jenkins
          jenkins_source_config_xml: "jenkins-configs/config.xml"
          jenkins_source_dir_configs: "jenkins-configs"
          jenkins_auth: "none"
          jenkins_config_owner: "ubuntu"
          jenkins_config_group: "ubuntu"

  tasks:
        - name: Ensure dependencies are installed
          apt:
            name:
              - default-jdk
              - curl
              - apt-transport-https
              - gnupg
            state: "{{ jenkins_state }}"

        - name: Add Jenkins apt repository key
          apt_key:
            url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
            state: "{{ jenkins_state }}"

        - name: Add Jenkins apt repository
          apt_repository:
            repo: deb https://pkg.jenkins.io/debian-stable binary/
            state: "{{ jenkins_state }}"
            update_cache: true

        - name: Download specific Jenkins version
          get_url:
            # http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_2.204.5_all.deb
            url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
            dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
          when: jenkins_version is defined

        - name: Install block
          block:
            - name: Install our specific version of Jenkins
              apt:
                deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
                state: "{{ jenkins_state }}"
              when: jenkins_version is defined

          rescue:
            # edit the port that Jenkins runs on by editing
            # the Jenkins configuration file 
            - name: Set the port on which Jenkins runs
              lineinfile:
                backrefs: true
                dest: "{{ jenkins_init_file }}"
                regexp: '^HTTP_PORT='
                line: 'HTTP_PORT={{ jenkins_http_port }}'
              register: jenkins_http_config            - 
  
        - name: Install block
          block:
            - name: Install our specific version of Jenkins
              apt:
                deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
                state: "{{ jenkins_state }}"
              when: jenkins_version is defined

        - name: Set the port on which Jenkins runs
          lineinfile:    
            backrefs: true
            dest: "{{ jenkins_init_file }}"
            regexp: '^HTTP_PORT='
            line: 'HTTP_PORT={{ jenkins_http_port }}'
          register: jenkins_http_config   
        
        - name: Ensure main configuration file is up to date
          template:
            src: "{{ jenkins_source_config_xml }}"
            dest: "/var/lib/jenkins/config.xml"
            owner: "{{ jenkins_config_owner }}"
            group: "{{ jenkins_config_group }}"
            mode: 0644
        
        - name: restart jenkins
          service:
            name: jenkins
            state: restarted

        - name: let jenkins come up for the first time
          pause:
                  seconds: 30

        # grab initial Admin password
        #- name: Get init password Jenkins
        #  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
        #  changed_when: false
        #  register: result

        # display the initial Admin password on the screen
        #- name: Print init password Jenkins
        #  debug:
        #    var: result.stdout
